#!/bin/bash
#############################################################################
# Copyright (c) 2019, Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory
#
# Created by Marty McFadden, 'mcfadden8 at llnl dot gov'
# LLNL-CODE-733797
#
# All rights reserved.
#
# This file is part of UMAP.
#
# For details, see https://github.com/LLNL/umap
# Please also see the COPYRIGHT and LICENSE files for LGPL license.
#############################################################################
function free_mem {
    m=`grep MemFree /proc/meminfo | awk -v N=2 '{print $N}'`
    fm=$(((${m}/1024)/1024))
    echo $fm GB Free
}

function drop_page_cache {
  echo "Dropping page cache"
  sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'
}

function disable_swap {
  echo "Disabling swap"
  sudo swapoff -a
}

function turn_off_readahead {
  fs=`mount | grep intel | cut -d " " -f 1`
  sudo blockdev --setra 0 $fs
  ra=`sudo blockdev --getra $fs`
  echo "Read ahead set to $ra for $fs"
}

free_mem
disable_swap
turn_off_readahead
drop_page_cache
free_mem
