#!/bin/bash
#############################################################################
# Copyright 2017-2020 Lawrence Livermore National Security, LLC and other
# UMAP Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: LGPL-2.1-only
#############################################################################
m=`grep MemFree /proc/meminfo | awk -v N=2 '{print $N}'`
fm=$(((${m}/1024)/1024))
echo $fm GB Free
